---
os: linux
dist: bionic
language: python
cache:
  pip: true
services:
  - docker
install: ""
jobs:
  include:
    - name: s390x Build
      arch: s390x
      script: docker build -f Dockerfile-s390x .
    - name: ppc64le Build
      arch: ppc64le
      script: docker build -f Dockerfile-ppc64le .
    - name: aarch64 Build
      arch: arm64
      script: docker build -f Dockerfile-aarch64 .
