FROM quay.io/pypa/manylinux2014_aarch64
LABEL maintainer="mtreinish"
RUN /opt/python/cp35-cp35m/bin/pip install -U numpy scipy cython pybind
RUN /opt/python/cp36-cp36m/bin/pip install -U numpy scipy cython pybind
RUN /opt/python/cp37-cp37m/bin/pip install -U numpy scipy cython pybind
RUN /opt/python/cp37-cp38/bin/pip install -U numpy scipy cython pybind
